apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "localstore.fullname" . }}-config
  labels:
    {{- include "localstore.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.nodeEnv | quote }}
  PORT: {{ .Values.backend.env.port | quote }}
  JWT_EXPIRES_IN: {{ .Values.backend.env.jwtExpiresIn | quote }}
  CORS_ORIGIN: {{ .Values.backend.env.corsOrigin | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
