apiVersion: v1
kind: Secret
metadata:
  name: {{ include "localstore.fullname" . }}-secrets
  labels:
    {{- include "localstore.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  DATABASE_URL: {{ include "localstore.databaseUrl" . | quote }}
